package pt.isel

/**
 * Represents an event.
 * @property id the event's id, generated by the android agenda
 * @property calendarId the calendar's id generated by the android agenda
 * @property title the event's title
 */
data class Event(
    val id: Long,
    val calendarId: Long,
    val title: String,
    //TODO may add creator [User] later
) {
    init {
        require(id >= 0) { "id must be positive" }
        require(calendarId >= 0) { "calendarId must be positive" }
        require(title.isNotBlank()) { "title must not be blank" }
        require(title.length <= MAX_TITLE_LENGTH) {
            "title must not be longer than $MAX_TITLE_LENGTH"
        }
    }

    companion object {
        const val MAX_TITLE_LENGTH = 50
    }
}
